//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use async_trait::async_trait;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub display_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, _db: &C, _insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let mut this = self;
        if let sea_orm::ActiveValue::Set(ref password) = this.password_hash {
            // Simple check to avoid re-hashing if it looks like an argon2 hash
            if !password.starts_with("$argon2") {
                match crate::utils::password::hash_password(password) {
                    Ok(hashed) => this.password_hash = sea_orm::ActiveValue::Set(hashed),
                    Err(e) => return Err(DbErr::Custom(format!("Failed to hash password: {}", e))),
                }
            }
        }
        Ok(this)
    }
}
