//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "word_sentences")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub word_id: Uuid,
    pub sentence_id: Uuid,
    pub created: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sentences::Entity",
        from = "Column::SentenceId",
        to = "super::sentences::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Sentences,
    #[sea_orm(
        belongs_to = "super::words::Entity",
        from = "Column::WordId",
        to = "super::words::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Words,
}

impl Related<super::sentences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sentences.def()
    }
}

impl Related<super::words::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Words.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
