//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "words")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub word: String,
    pub phonics: Option<String>,
    pub part_of_speech: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub vietnamese_meaning: String,
    pub image_url: Option<String>,
    pub word_audio_url: Option<String>,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::word_sentences::Entity")]
    WordSentences,
}

impl Related<super::word_sentences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WordSentences.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
